Macierz A jest symetryczna
ma rzeczywiste wartości własne
jej unormowany wektory tworzą bazę ortonormalną w R^n

Znajdź dwie wartości własne i dwa odpowiadające im wektory własne

In [26]:
import numpy as np

In [27]:
A = np.matrix([[19/12, 13/12, 5/6, 5/6, 13/12, -17/12],
               [13/12, 13/12, 5/6, 5/6, -11/12, 13/12],
               [5/6, 5/6, 5/6, -1/6, 5/6, 5/6],
               [5/6, 5/6, -1/6, 5/6, 5/6, 5/6],
               [13/12, -11/12, 5/6, 5/6, 13/12, 13/12],
               [-17/12, 13/12, 5/6, 5/6, 13/12, 19/12]])


# funkcja obliczająca normę euklidesowa
def norm_of_vector(vector):
    norm_value = np.sqrt(vector.T@vector)
    return norm_value



random_vector = np.matrix([3,5,6,7,8,2])
# vector_x0 = random_vector / norm_of_vector(random_vector)


eigenvector_xk = A@random_vector.T
print("first", eigenvector_xk)

eigenvectors_list = list()
eigenvalues_list = list()

k=0

while True:
    vector_zk = A@eigenvector_xk
#     print(k, "\n\n","mnozymy przez A", "\n", new_vector_xk)
    
    #normalizuje
#     norm_of_vector_zk = np.sqrt(vector_zk.T@vector_zk)
    norm_of_vector_zk = norm_of_vector(vector_zk)
    
    
    
#     print("\n\n", "norma wektora", "\n", norm_of_vector_xk)
    eigenvector_xk_1 = vector_zk / norm_of_vector_zk
#     print("\n\n", "znormalizowany", "\n", eigenvector_xk_1)
   

    # sprawdzam czy się jeszcze zmienia
    vector_distinction = np.abs(eigenvector_xk_1 - eigenvector_xk)
    value = all(element < 0.001 for element in vector_distinction)
    if value == True:
        break
        
#     print ("\n\n", "różnica","\n", np.abs(eigenvector_xk_1 - eigenvector_xk))
    eigenvector_xk = eigenvector_xk_1
#     print("jedziemy dalej")
    k+=1

    
print(k)
eigenvectors_list.append(eigenvector_xk_1)    
print("\n\n Wektor własny do największej wartości własnej: \n", eigenvector_xk_1)
eigenvalue_xk = norm_of_vector_zk
eigenvalues_list.append(eigenvalue_xk)
print("\n\n Największa wartość własna do wektora własnego: ", eigenvalue_xk)
    

    



first [[26.83333333]
 [14.33333333]
 [18.83333333]
 [19.83333333]
 [20.33333333]
 [23.83333333]]
9


 Wektor własny do największej wartości własnej: 
 [[0.40999294]
 [0.40811212]
 [0.40824711]
 [0.40824713]
 [0.40822787]
 [0.40665571]]


 Największa wartość własna do wektora własnego:  [[3.99999115]]


In [28]:
"e1 to jest nasz wektor własny obliczony w poprzednim zadaniu"

# random_vector = np.array([(-1)*element for ])
random_vector = [[0.40999294], [-0.40811212], [-0.40824711], [0.40824713], [0.40822787], [-0.40665571]]

max_eigenvector = eigenvector_xk_1 # wektro e1 największy obliczyliśmy w poprzedniej pętli
second_eigenvector_xk = eigenvector_xk_1

j=0

while True:
    vector_zk = A@second_eigenvector_xk
#     print("\n\n  \n")
    vector_zk = vector_zk - max_eigenvector@(max_eigenvector.T@vector_zk)
#     print("\n\n  \n")
    
#     
    
    
    second_eigenvector_xk_1 = vector_zk / norm_of_vector(vector_zk)
    print("\n\n", norm_of_vector(vector_zk) ,"  \n")
    
    # sprawdzam czy się jeszcze zmienia
    vector_distinction = np.abs(second_eigenvector_xk_1 - second_eigenvector_xk)
    value = all(element < 0.001 for element in vector_distinction)
    if value == True:
        break
    
    second_eigenvector_xk = second_eigenvector_xk_1
    print( "\n\n", j, "\n\n", second_eigenvector_xk_1)
    j+=1
    
print (second_eigenvector_xk_1) 
print("\n\n", j)
# second_eigenvalue

eigenvectors_list.append(second_eigenvector_xk_1)
eigenvalues_list.append(norm_of_vector(vector_zk))




 [[0.00254022]]   



 0 

 [[-0.83823905]
 [ 0.22872043]
 [ 0.00098063]
 [ 0.00095838]
 [ 0.13759053]
 [ 0.47550945]]


 [[2.88355548]]   



 1 

 [[-0.55606316]
 [-0.09388483]
 [ 0.00090336]
 [ 0.00089564]
 [-0.15709155]
 [ 0.81074042]]


 [[2.94456047]]   



 2 

 [[-0.78117474]
 [ 0.10828555]
 [ 0.00096758]
 [ 0.00096496]
 [ 0.06535429]
 [ 0.61136504]]


 [[2.97455507]]   



 3 

 [[-0.64354502]
 [-0.04234718]
 [ 0.00094862]
 [ 0.00094774]
 [-0.07121294]
 [ 0.76090962]]


 [[2.98852673]]   



 4 

 [[-0.74259436]
 [ 0.04925958]
 [ 0.00096653]
 [ 0.00096624]
 [ 0.02994177]
 [ 0.66725463]]


 [[2.99487006]]   



 5 

 [[-0.6793732 ]
 [-0.01839134]
 [ 0.00095894]
 [ 0.00095884]
 [-0.03129203]
 [ 0.73289343]]


 [[2.99771638]]   



 6 

 [[-0.72292117]
 [ 0.02248244]
 [ 0.00096525]
 [ 0.00096522]
 [ 0.01387534]
 [ 0.69042388]]


 [[2.99898682]]   



 7 

 [[-0.69447112]
 [-0.00764779]
 [ 0.00096178]
 [ 0.00096177]
 [-0.01338789]
 [ 0.71935407]]


 [[2.99955253]]   



 8 

 [[

In [29]:
eigenvector_xk_1.T@second_eigenvector_xk_1
print(eigenvectors_list, "\n\n\n", eigenvalues_list)

[matrix([[0.40999294],
        [0.40811212],
        [0.40824711],
        [0.40824713],
        [0.40822787],
        [0.40665571]]), matrix([[-0.70643999],
        [ 0.00133695],
        [ 0.00096342],
        [ 0.00096342],
        [ 0.00118733],
        [ 0.70776937]])] 


 [matrix([[3.99999115]]), matrix([[3.00000488]])]
